# Dependencies
markdown:         redcarpet	
redcarpet:
  extensions: ["tables"]

highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nicholas Tierney
tagline:          'Original witty remark'
description:      'Statistics, Coffee, Photography, and Me'
url:              tierneyn.github.io
baseurl:          /

author:
  name:           'Nicholas Tierney'
  url:            tierneyn.github.io

paginate:         5

# exclude the R Project
exclude:          [_rmd, _rmd.Rproj]
exclude: ["*.Rmd"]
