# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nicholas Tierney
tagline:          'Original witty remark'
description:      'This is my website'
url:              tierneyn/github.io
baseurl:          /

author:
  name:           'Nicholas Tierney'
  url:            https://www.njtierney.com

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/tierneyn
  repo:           https://github.com/tierneyn
