# Dependencies
markdown:         redcarpet	
redcarpet:
  extensions: ["tables"]

highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
name:             njtierney
title:            Nicholas Tierney
tagline:          'Original witty remark'
description:      'Statistics, Coffee, Photography, and Me'
url:              http://tierneyn.github.io
baseurl:          

author:
  name:           'Nicholas Tierney'
  url:            tierneyn.github.io

paginate:         100
paginate_path:    "blog/page:num/"

# exclude the R Project
exclude: ["*.Rmd"]
exclude: ["*.Rproj"]
exclude: [".RData"]
exclude: [".Rhistory"]

