# Dependencies
markdown:         kramdown
highlighter:      rouge
extensions: ["tables"]
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
name:             njtierney
title:            Nicholas Tierney
tagline:          'Original witty remark'
description:      'Statistics and R Enthusiast'
url:              http://njtierney.github.io
baseurl:          

author:
  name:           'Nicholas Tierney'
  url:            njtierney.github.io

paginate:         100
paginate_path:    "blog/page:num/"

# exclude the R Project
exclude: ["*.Rmd"]
exclude: ["*.Rproj"]
exclude: [".RData"]
exclude: [".Rhistory"]

